workspace:
  base: /go
  path: src/github.com/endiangroup/golang-url-shortener

pipeline:
  prepare:
    image: golang:latest
    commands:
      - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      - . $HOME/.nvm/nvm.sh
      - nvm install stable
      - nvm use stable
      - make prepare

  test:
    image: golang:latest
    commands:
      - make test

  build-staging:
    image: golang:latest
    commands:
      - go get -v github.com/mitchellh/gox
      - apt-get update && apt-get -y install gettext-base
      - printenv
      - make buildStaging
    secrets: [ redis_url, google_clientid, google_secret ]

  ecr:
    image: plugins/ecr
    region: eu-west-2
    repo: 189356475589.dkr.ecr.eu-west-2.amazonaws.com/ndn.sh
    registry: 189356475589.dkr.ecr.eu-west-2.amazonaws.com
